/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisNovoRouteImport } from './routes/imoveis/novo'
import { Route as ImoveisPropertyIdRouteImport } from './routes/imoveis/$propertyId'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisNovoRoute = ImoveisNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ImoveisRoute,
} as any)
const ImoveisPropertyIdRoute = ImoveisPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => ImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/imoveis/$propertyId': typeof ImoveisPropertyIdRoute
  '/imoveis/novo': typeof ImoveisNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/imoveis/$propertyId': typeof ImoveisPropertyIdRoute
  '/imoveis/novo': typeof ImoveisNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/imoveis/$propertyId': typeof ImoveisPropertyIdRoute
  '/imoveis/novo': typeof ImoveisNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/contato'
    | '/faq'
    | '/imoveis'
    | '/leads'
    | '/login'
    | '/sobre'
    | '/imoveis/$propertyId'
    | '/imoveis/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/contato'
    | '/faq'
    | '/imoveis'
    | '/leads'
    | '/login'
    | '/sobre'
    | '/imoveis/$propertyId'
    | '/imoveis/novo'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/contato'
    | '/faq'
    | '/imoveis'
    | '/leads'
    | '/login'
    | '/sobre'
    | '/imoveis/$propertyId'
    | '/imoveis/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/novo': {
      id: '/imoveis/novo'
      path: '/novo'
      fullPath: '/imoveis/novo'
      preLoaderRoute: typeof ImoveisNovoRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/imoveis/$propertyId': {
      id: '/imoveis/$propertyId'
      path: '/$propertyId'
      fullPath: '/imoveis/$propertyId'
      preLoaderRoute: typeof ImoveisPropertyIdRouteImport
      parentRoute: typeof ImoveisRoute
    }
  }
}

interface ImoveisRouteChildren {
  ImoveisPropertyIdRoute: typeof ImoveisPropertyIdRoute
  ImoveisNovoRoute: typeof ImoveisNovoRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisPropertyIdRoute: ImoveisPropertyIdRoute,
  ImoveisNovoRoute: ImoveisNovoRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
