create table if not exists properties (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text unique,
  short_description text,
  full_description text,
  purpose text not null check (purpose in ('venda', 'locacao')),
  type text not null,
  price numeric,
  neighborhood text,
  city text default 'Santarém',
  state text default 'PA',
  location_text text,
  total_area numeric,
  built_area numeric,
  bedrooms integer default 0,
  suites integer default 0,
  bathrooms integer default 0,
  parking_spaces integer default 0,
  status text not null default 'rascunho' check (status in ('rascunho', 'publicado', 'vendido', 'alugado', 'indisponivel')),
  featured boolean default false,
  internal_notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  published_at timestamp with time zone
);